# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCyKnFUeOJfVGw22uhtevtGc6rTC_nqw
"""

#GRAPH
import sys
class graph:
    def __init__(self):
        self.nodes=[]
        self.graph=[]
        self.nodecount=0

    def addNode(self,v):
        if v in self.nodes:
            print(v,"is already present")
        else:
            self.nodecount+=1
            self.nodes.append(v)
            # Expand existing rows with a new column (0)
            for row in self.graph:
                row.append(0)
            # Add a new row with 'self.nodecount' zeros
            new_row = [0] * self.nodecount
            self.graph.append(new_row)
            print(v,"is added")


    def printGraph(self):
        print("Nodes:", *self.nodes)
        print("Adjacency Matrix:")
        if self.nodecount == 0:
            print("Graph is empty.")
            return # Corrected: Removed '1' and '1' after return

        print("  ", end="")
        for node in self.nodes:
            print(f"{node:<2}", end=" ")
        print()

        for i in range(self.nodecount):
            print(f"{self.nodes[i]:<2}", end=" ")
            for j in range(self.nodecount):
                print(f"{self.graph[i][j]:<2}",end=" ")
            print()


    def addEdge_undirected_unweighted(self,v1,v2):
      if v1 not in self.nodes:
        print(v1,"not present")
        return
      if v2 not in self.nodes:
        print(v2,"not present")
        return
      index1=self.nodes.index(v1)
      index2=self.nodes.index(v2)
      self.graph[index1][index2]=1
      self.graph[index2][index1]=1
      print("edge added")

    def addEdge_undirected_weighted(self,v1,v2,weight):
      if v1 not in self.nodes:
        print(v1,"not present")
        return
      if v2 not in self.nodes:
        print(v2,"not present")
        return
      index1=self.nodes.index(v1)
      index2=self.nodes.index(v2)
      self.graph[index1][index2]=int(weight)
      self.graph[index2][index1]=int(weight)
      print("edge added")

    def addEdge_Directed_weighted(self, v1, v2, weight):
      if v1 not in self.nodes:
        print(v1,"not present")
        return
      if v2 not in self.nodes:
        print(v2,"not present")
        return
      index1=self.nodes.index(v1)
      index2=self.nodes.index(v2)
      self.graph[index1][index2]=int(weight)
      print("edge added")

    def deleteGraph(self, v):
      if v not in self.nodes:
        print(v,"not present")
      else:
           index_to_remove = self.nodes.index(v)
           self.nodes.pop(index_to_remove)
           self.nodecount -= 1 # Corrected: access as self.nodecount

           # Remove row corresponding to the deleted node
           self.graph.pop(index_to_remove)

           # Remove column corresponding to the deleted node
           for i in range(self.nodecount):
             self.graph[i].pop(index_to_remove)
           print(v, "node deleted")

if __name__ =="__main__":
    obj=graph()
    while True:
        print("\n1.(Insertion) add a node using adjacency matrix representation")
        print("2.(Insertion) add a edge adjacency matrix representation ")
        print("3.(Insertion) add a edge undirected weighted graph")
        print("4.(Insertion) add a edge directed weighted graph")
        print("5.print graph")
        print("6. Delete Operation")
        print("0.exit\n")
        try:
            n=int(input("enter your choice"))
        except ValueError:
            print("Invalid input. Please enter a number between 0 and 6.")
            continue

        if n==1:
            v=input("enter vertex:")
            obj.addNode(v)
        elif n==2:
            v1=input("enter vertex1:")
            v2=input("enter vertex2:")
            obj.addEdge_undirected_unweighted(v1,v2)
        elif n==3:
          v1=input("enter vertex1:")
          v2=input("enter vertex2:")
          v3=input("enter weight:")
          obj.addEdge_undirected_weighted(v1,v2,v3)
        elif n==4:
          v1=input("enter vertex1:")
          v2=input("enter vertex2:")
          v3=input("enter weight:")
          obj.addEdge_Directed_weighted(v1,v2,v3)
        elif n==5:
            obj.printGraph()
        elif n==6:
            v_del = input("Enter the vertex to delete:")
            obj.deleteGraph(v_del)
        elif n==0:
            sys.exit(0)
        else:
            print("Invalid choice. Please enter a number between 0 and 6.")

#INHERITANCE single level

class A:
  def showA(self):
     print("i am in class A")
class B(A)
   def showB(self):
     print("i am in class B")
if __name__ =='__main__':
  obj=B()
  obj.showA()
  obj.showB()

#Multilevel

class A:
  def showA(self):
     print("i am in class A")
class B(A)
   def showB(self):
     print("i am in class B")

     class C(B):
  def showB(self):
     print("i am in class c")
if __name__ =='__main__':
  obj=B()
  obj.showA()
  obj.showB()
  obj.showC()

class A:
  def show(self):
     print("i am in class A")
class B(A)
   def show(self):
     print("i am in class B")

     class C(A,B):
  def showC(self):
     print("i am in class c")
if __name__ =='__main__':
  obj=C()
  obj.showC()

#overloading

def add(a):
  print(a)

def add(a,b):
  print(a+b)

def add(a,b,c):
  print(a+b+c)

class Parent:
  def __init__(self):
    self.speed=100
    print("cash,gold")

  def bike(self)
  print("splender+",self.speed)

class child(parent):
  def __init__(self):
    self.speed=150
  def bike(self):
    print("HB",self.speed)

   obj=child()
   obj.bike()