# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vma92h90TWkf5oba0a0jZkgXL1V3DtBP
"""

class mergesorts:
  def mergesort (self,arr1,arr2):
    arr3=[]
    i=0
    j=0
    k=0
    while i<len(arr1) and j<len(arr2):
       if arr1[i]<arr2[j]:
         arr3.append(arr1[i])
         i+=1
         k+=1
       else:
        arr3.append(arr2[j])
        j+=1
        k+=1
    return arr3
if __name__ =="__main__":
  obj=mergesorts()
  arr1=[1,3,5]
  arr2=[2,4,6]
  ans=obj.mergesort(arr1,arr2)
  print(ans)

class mergesorts:
  def mergesort (self,arr1,arr2):
    arr3=[]
    i=0
    j=0
    k=0
    while i<len(arr1) and j<len(arr2):
       if arr1[i]<arr2[j]:
         arr3.append(arr1[i])
         i+=1
         k+=1
       else:
        arr3.append(arr2[j])
        j+=1
        k+=1
    # Append remaining elements of arr1, if any
    while i<len(arr1):
         arr3.append(arr1[i])
         i+=1
         k+=1
    # Append remaining elements of arr2, if any
    while j<len(arr2):
        arr3.append(arr2[j])
        j+=1
        k+=1
    return arr3
if __name__ =="__main__":
  obj=mergesorts()
  arr1=[1,3,5,7,9]
  arr2=[2,4,6]
  ans=obj.mergesort(arr1,arr2)
  print(ans)

class mergesorts:
  def mergesorts (self,arr):
    if len(arr)>1:

      mid=len(arr)//2
      arr1=arr[:mid]
      arr2=arr[mid:]
      self. mergesorts(arr1)
      self.mergesorts(arr2)
      i=0
      j=0
      k=0
      while i<len(arr1) and j<len(arr2):
        if arr1[i]<arr2[j]:
         arr[k]=arr1[i]
         i+=1
         k+=1
        else:
          arr[k]=arr2[j]
          j+=1
          k+=1
      while i<len(arr1):
         arr[k]=arr1[i]
         i+=1
         k+=1
    # Append remaining elements of arr2, if any
      while j<len(arr2):
        arr[k]=arr2[j]
        j+=1
        k+=1

if __name__ =="__main__":
  obj=mergesorts()
  arr=[1,3,5,7,2,4,9,10,12,16]
  obj.mergesorts(arr)
  print(arr)



import sys
class GetNode:
  def __init__(self):
    self.data=None
    self.next=None
class Linkedlist:
  def __init__(self):
    self.head=None
  def append(self):
      data=int(input("enter the data:"))
      newNode=GetNode
      newNode.data=data
      if self.head== None:
        self.head=newNode
      else:
        ptr=self.head
        while ptr.next!=None:
          ptr=ptr.next
        ptr.next=newNode
        print("data is added")
  def traverse(self):
    if self.head==None:
      print("linked list is empty")
    else:
      ptr=self.head
      while ptr!=None:
        print(ptr.data,"->",end="")
        ptr=ptr.next
    def addatbegin(self):
      data=int(input("enter data"))
      newNode=GetNode()
      newNode.data=data
      if self.head==None:
if __name__ =="__main__":
    obj=Linkedlist()
    while True:
        print("1.append")
        print("2.traverse")
        print("0.exit")
        n=int(input("enter your choice"))
        if n==1:
         obj.append()
        elif n==2:
         obj.traverse()
        elif n==0:
         sys.exit(0)

import sys
class GetNode:
  def __init__(self):
    self.data=None
    self.next=None
class Linkedlist:
  def __init__(self):
    self.head=None
  def append(self):
      data=int(input("enter the data:"))
      newNode=GetNode()
      newNode.data=data
      if self.head== None:
         self.head=newNode
      else:
        ptr=self.head
        while ptr.next!=None:
          ptr=ptr.next
        ptr.next=newNode
        print("data is added")
  def traverse(self):
    if self.head==None:
      print("linked list is empty")
    else:
      ptr=self.head
      while ptr!=None:
        print(ptr.data,"->",end="")
        ptr=ptr.next
  def addinbetween(self):
    data=int(input("enter the data"))
    key=int(input("enter the key"))
    newNode=GetNode()
    newNode.data=data
    if self.head==None:
      self.head=newNode
    else:
      ptr=self.head
      while ptr.next!=None:
        if ptr.data==key:
          break
        else:
          ptr=ptr.next
          if ptr.next==None:
            print("key not found")
          else:
            ptr1=ptr.next
            ptr.next=newNode
            newNode.next=ptr1
            print("data is added")
if __name__ =="__main__":
    obj=Linkedlist()
    while True:
        print("1.append")
        print("2.traverse")
        print("3.add in between")
        n=int(input("enter your choice"))
        if n==1:
         obj.append()
        elif n==2:
         obj.traverse()
        elif n==3:
         obj.addianbetween()
        elif n==0:
            sys.exit(0)

import sys
class GetNode:
  def __init__(self):
    self.data=None
    self.next=None
class Linkedlist:
  def __init__(self):
    self.head=None
  def append(self):
      data=int(input("enter the data:"))
      newNode=GetNode()
      newNode.data=data
      if self.head== None:
         self.head=newNode
      else:
        ptr=self.head
        while ptr.next!=None:
          ptr=ptr.next
        ptr.next=newNode
        print("data is added")
  def traverse(self):
    if self.head==None:
      print("linked list is empty")
    else:
      ptr=self.head
      while ptr!=None:
        print(ptr.data,"->",end="")
        ptr=ptr.next
  def addinbetween(self):
    data=int(input("enter the data"))
    key=int(input("enter the key"))
    newNode=GetNode()
    newNode.data=data
    if self.head==None:
      self.head=newNode
    else:
      ptr=self.head
      while ptr.next!=None:
        if ptr.data==key:
          break
        else:
          ptr=ptr.next
          if ptr.next==None:
            print("key not found")
          else:
            ptr1=ptr.next
            ptr.next=newNode
            newNode.next=ptr1
            print("data is added")
    def deleteAtBegin(self):
      if head==None:
        print('list not present')
      else:
        ptr=self.head
        ptr1=ptr.next
        head=ptr1
        print(ptr.data,"is deleted")
     def deleteAtEnd(self):
      if head==None:
        print("list not present")
      else:
        ptr=self.head
        while ptr.next.next!=None:
          ptr1=ptr
          ptr=ptr.next



if __name__ =="__main__":
    obj=Linkedlist()
    while True:
        print("1.append")
        print("2.traverse")
        print("3.add in between")
        n=int(input("enter your choice"))
        if n==1:
         obj.append()
        elif n==2:
         obj.traverse()
        elif n==3:
         obj.addianbetween()
        elif n==4:
          obj.deleteAtBegin()
        elif n==0:
            sys.exit(0)