# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Nye805E8M1r3Xt9qgCEI-H2bUe48dfA
"""

#HASHING

class hashtable:
    def __init__(self,size):
      self.size=size
      self.table=[]
      for i in range(size):
        self.table.append([])

    def hash_function(self,key):
      return key % self.size

    def insert(self,key=35):
      index=self.hash_function(key)
      self.table[index].append(key)

    def display(self):
      for x in range(10):
        print(self.table[x])
h= hashtable(10)
h.insert(15)
h.insert(25)
h.insert(35)
h.display()

#linear probing
class LinearProbing:
  def __init__(self,size):
      self.size=size
      self.table=[None]*size

  def hash_function(self,key):
      return key % self.size

  def insert(self,key):
      index=self.hash_function(key)

      while self.table[index] is not None:
        index=(index+1)%self.size

      self.table[index] =key
  def display(self):
    print(self.table)

h= LinearProbing(10)
h.insert(15)
h.insert(25)
h.insert(35)
h.display()

#BUILD HASH FUNCTION

class MyHashtable:
  def __init__(self,size):
      self.size=size
      self.table=[[] for i in range(size)]

  def hash_function(self,key):
    return key % self.size

  def insert(self,key,value):
    index= self.hash_function(key)
    self.table[index].append((key,value))

  def search(self,key):
    index = self.hash_function(key)
    for k,v in self.table[index]:
      if k == key:
        return v
    return "Not found"

  def delete(self,key):
      index = self.hash_function(key)

      # Iterate through the specific bucket identified by the hash index
      # Using enumerate to get both index (i) and the (k,v) pair
      for i,(k,v) in enumerate(self.table[index]):
        if k==key:
          del self.table[index][i]
          return

  def display(self):
      print(self.table)


h= MyHashtable(10)
h.insert(1,"teju")
h.insert(12,"pranav")

print(h.search(12))
h.display()
h.delete(12)
h.display()

#REGULAR EXPRESSION:

import re
count=0
pattern=re.compile("ab") # Changed re.compiler to re.compile
matcher=pattern.finditer("abaababaab") # Corrected syntax for calling finditer on a compiled pattern
for match in matcher:
  count+=1
  print(match.start(),'...',match.end(),'...',match.group())
print('total no of group occurences:',count)

import re
count=0
#pattern=re.compiler("ab")
#matcher=pattern,finditer("abaababaab")
for match in matcher:
  count+=1
  print(match.start(),'...',match.end(),'...',match.group())
print('total no of group occurences:',count)

import re
#x="[abc]"
#x="[^abc]"
#x='[a-z]'
#x='[0-9]'
#x='[a-zA-Z0-9]'
#x='[^a-zA-Z0-9]'
matcher=re.finditer(x,"a7bdD23@k2$D8z")
for match in matcher:
     print(match.start(),'...',match.end(),'...',match.group())

#predifined character classes

#x='\\s'
#x='\\S'
#x='\\d'
#x='\\D'
#x='\\w'
#x='\\W'
#x="."
matcher=re.finditer(x,"a7bdD23@k2$D8z")
for match in matcher:
     print(match.start(),'...',match.end(),'...',match.group())

#x='a'
#x='a+'
#x='a*'
#x='a?'
x='a{3}'
#x='a{2,3}'
matcher=re.finditer(x,"aaaaabbaababbaa")
for match in matcher:
     print(match.start(),'...',match.end(),'...',match.group())

import re
str=input("enter any string:")
m=re.match(str,"abc@xyz_pqr*")
if m!=None:
  print("yes matching is  available at begining of string")
  print('start index:',m.start(),'. end index:',m.end())
else:
  print('matching is not available at begining')

#fullmatch

import re
str=input("enter any string:")
m=re.fullmatch(str,"abc@xyz_pqr*")
if m!=None:
  print("yes matching is  available" )
else:
  print('matching is not available ')

#findall
import re
list=re.findall('[0-9]','abc123@12607teju')
print(list)
for x in list:
  print(x)

import re
str=re.sub('[0-9]','$','abc123@12607teju')
print(str)
print(type(str))

import re
number=input("enter mobile number")
match=re.fullmatch("[6-9]\\d{9}",number)
if match!=None:
  print("valid mobile number")
else:
  print("invalid mobile number")