# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tB1vgBXtHnlCGBOFca-gBoyjsFgvPRq2
"""

#BST
import sys
class BST:
  def __init__(self,key=None):
    self.leftchild=None
    self.data=key
    self.rightchild=None

  def search(self, key):
    if self.data is None:
      print(f"{key} not found (tree is empty).")
      return False
    elif self.data == key:
      print(f"{key} is found.")
      return True
    elif key < self.data:
      if self.leftchild:
        return self.leftchild.search(key)
      else:
        print(f"{key} not found (reached end of left branch).")
        return False
    elif key > self.data:
      if self.rightchild:
        return self.rightchild.search(key)
      else:
        print(f"{key} not found (reached end of right branch).")
        return False
    return False # Should not be reached under normal circumstances

  def insert (self,key):
    if self.data==None:
      self.data=key
      return
    elif self.data==key:
        return
    else:
      if key<self.data:
        if self.leftchild:
          self.leftchild.insert(key)
        else:
          self.leftchild=BST(key)
      elif key>self.data:
        if self.rightchild:
          self.rightchild.insert(key)
        else:
          self.rightchild=BST(key)

  def preorder(self):
    print(self.data,end=" -> ")
    if self.leftchild:
      self.leftchild.preorder()
    if self.rightchild:
      self.rightchild.preorder()

  def postorder(self):
    if self.leftchild:
      self.leftchild.postorder()
    if self.rightchild:
      self.rightchild.postorder()
    print(self.data,end=" -> ")

  def inorder(self):
    if self.leftchild:
      self.leftchild.inorder()
    print(self.data,end=" -> ")
    if self.rightchild:
      self.rightchild.inorder()

if __name__ == '__main__':
      root=BST()
      while True:
        print("1. insert")
        print("2. search")
        print("3. preorder")
        print("4. postorder")
        print("5. inorder")
        print("0. Exit")
        n=int(input("select any choice"))
        if n==1:
          arr=[36,26,46,21,31,11,24,41,56,51,66]
          for i in range(len(arr)):
            root.insert(arr[i])
        elif n==2:
            search_key = int(input("Enter key to search: "))
            root.search(search_key)
        elif n==3:
            root.preorder()
        elif n==4:
            root.postorder()
        elif n==5:
            root.inorder()
        elif n==0:
            sys.exit(0)

#recurssion for factorial

def fact(n):
  if n==0 and n==1
  return 1
  else:
    return n*fact(n-1)
if __name__ == '__main__':
  n=5
  res=fact(n)
  print(res)

def multiply (x,y):
  if y==1:
    return x
  elif x==1:
      return y
  elif x==0 or y==0:
        return 0
   else:
    return x+multiply(x,y-1)

if __name__ == '__main__':
  x=2
  y=3
  res=multiply(x,y)
  print(res)

def power (x,y):
  if x==1:
    return 1
  elif x==0:
    return 0
  elif y==1:
    return x
  elif y==0:
    return 1
  else:
    return x*power(x,y-1)

if __name__ == '__main__':
    x=2
    y=3
    res=power(x,y)
    print(res)

#find sum of N using recurssion
def sum(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
      return n+sum(n-1)

  if __name__ == '__main__':
    n=10
    res=sum(n)
    print(res)

def fibo(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return fibo(n-1)+fibo(n-2)
n=10
for x in range(n):
  print(fibo(x),end =" ")

import itertools
def generate_permutations(number):
  number_str=str(number)
  perm =permutations(a)
  for i in perm:
    print(i)